import math

"""
Given a string of DNA, return four integers separated by spaces counting the respective
count of each nucleotide
"""

seq = 'GTAGACAATAGCCGCCGCCTGATTACTTGCGGTGGTACACTGCGTGGACCGGGGGAGCCCTTAACGTACACTGGAGTTGCGCACTAGGATTGCGATTCCGCCGTGATAATCTAATCTCGGTACGAGTTAGACCGGGATACATCCAACTACAGCACGTCTACCTTATATTCAGATGGGTGTACAACCACATTTCACGCGAGGCTCCACTCGGTAGCATGAAGCTTCCCTTGTTGAACGAGTTACATCAGCTCGTGATCACAACAGCCTAACCCCGGACCGACACCTTACCGGATCTCTGGCAGGAGCGTAAGCCTAGGATGCAGCGGTCTTATCTTATAGACTTTATTACCGTAAAGGCAGGCTAGATCACGCTACGAGTCAGTCTTAGCAGGAAACGTGTTTAAAATAATCCAAGGCACTACAGCACTTGGTCCGAGCGCACTTCACAGAGAAACTGGTTCAGGCGTACAGTACTGTCACGCGAGGGTCTACCCATCGTGAAGACCCTGGGGGCTGTCCCTATACCCGTTCGAGTCACCCTGACAAACATGCTAGACGACATGCGAGCCTATATGTTACGGACTGGACCCCTCAAGTACATAGATCGTGTCGCGACGACAACCATTGTGGTTCCGATGCTTCTCATGAGTTACGATTGATAATGGAGATAAAACAGGAAACTAAAAACCAGACTCAATTCGCTTCTTGATCTTTCAGGGTTTAGTAGCGCCATGATGACCCCTCAGTAGTCTCGAATGTCTTGGACGTGCGGGAGATGTGCTGAGACCGCAAGATGAAACTACACGCCCCGCAAGT'

a = 0
c = 0
g = 0
t = 0

for nt in seq:
	if nt == 'A': 
		a += 1
	elif nt == 'C':
		c += 1
	elif nt == 'G':
		g += 1
	else:
		t += 1

print(a, '', c, '', g, '', t)